{
    'name': 'Real Estate',
    'version': '1.0.0',
    'summary': 'Real Estate module for odoo',
    'description': 'Real Estate module for odoo',
    'category': 'Sales',
    'author': 'Raistdev',
    'website': '',
    'license': 'GPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/estate_property_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_property_offer_views.xml',
        'views/res_users_views.xml',
        'views/estate_menus.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
